### ISSUE TITLE
Periodicals Encoding 

### ISSUE THREAD

**Issue by cmccraw** [cmccraw/LiliElbe_EngagedLearners#17]
Bumping posted issue from @natashaaranda:

"@RJP43 I am working on the header for the periodical 1931-11-28socialdemokraten. The author is unknown, is there a key for an unknown author❓ Also what is the format for encoding subheadlines? If the periodical is in question and answer format, do you attribute each section to whoever is speaking, and what is the format when the author is unknown?
Thank you
😃"

@RJP43 I suspect the Encoding Project Group might have a few questions about how to encode some of the periodicals, since a bit of it is unprecedented. Let me know if you think it would be helpful to arrange a Zoom or Google Hangouts meeting with their group!

@natashaaranda could you and your groupmates assemble a full list of questions that you have about encoding the periodicals? 

Thanks!

**Comment by RJP43** [comment]
hey @cmccraw and @natashaaranda I hope I have helped to answer the question [here - in the original thread](https://github.com/cmccraw/LiliElbe_EngagedLearners/issues/11#issuecomment-546634966). My apologies for the late response. 😭 💟   

I am available for meetings Monday and Tuesday next week if any encoders would like to schedule a session / live proofing of their XML. Updates to the schema and prosopography should also be live by the end of the day today.   I can also get on here and answer a series of questions if that seems easier with the logistics of getting multiple group members together. Just please be sure to have the latest versions of your XML uploaded so I can see what you all are working with. 👍 😃    
  
Also, Happy Halloween-ish! 🎃
