### ISSUE TITLE
Group A + Group B Encoding Issues

### ISSUE THREAD

**Issue by cmccraw** [cmccraw/LiliElbe_EngagedLearners#8]
Post any technical questions or issues that you encounter while encoding here. 

+ Be sure to tag @cmccraw and any classmates/groupmates that you are working with, in case someone else has an answer. 

+ Be as specific as possible! Include the exact document name that you are working on, and as many details about the problem as possible (location, error messages, etc.). 

_Content-related issues (things that pertain to Dr. Caughie or Emily) should go under the "Questions for the Editor(s)" column on your [Hours Tracking Spreadsheet](https://docs.google.com/spreadsheets/d/1pnN_HHr5SKX0AgF3wYu3F1XlqMcjZK-rfms4DCGTQug/edit?usp=sharing)._

**Comment by coconnell22** [comment]
@cmccraw in the LEDA encoding guidelines under the Letters section it says "syle" instead of "style"

**Comment by MylinhLam213** [comment]
@cmccraw @ group A 

does anyone know where exactly to find the key ids for who translated the letter and who it was review by?

**Comment by cmccraw** [comment]
@coconnell22 thanks for catching that! Has been corrected :) 

@MylinhLam213 The initials for team members can be found in the "Capturing Metadata" lesson— https://github.com/cmccraw/LiliElbe_EngagedLearners/wiki/Lesson-%238:-Capturing-Metadata. Which is certainly important! I'll be sure to add this links to our "Quick Links" on the homepage.

**Comment by JBrockland** [comment]
@cmccraw I tried to upload my file, but github tells me "Uploads are disabled"
